---

name: coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: coverage

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: false
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install

      - name: Start Docker
        run: |
          docker compose up -d localstack

      - name: Run Tests
        run: |
          npm run test:coverage

      - name: Stop Docker
        run: |
          npm run aws:local:stop

      - name: Update Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: success()
